version: '2'
services:

  pylibs-builder-test:
    image: pylibs-builder:latest
    links:
      - mysql-server:unit_test-mysql
    tty: true
    stdin_open: true
    depends_on:
      - mysql-server
    volumes:
      - ./api-framework/target:/pylibs/api-framework/target
      - ./sqllib/target:/pylibs/sqllib/target

  mysql-server:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_USER=wombat
        - MYSQL_PASSWORD=1wombat2
        - MYSQL_DATABASE=test
      ports:
          - 3306:3306
